-- AlterTable
ALTER TABLE "CashUp" ADD COLUMN "cashExpenses" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "CashUp" ADD COLUMN "countedCard" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "CashUp" ADD COLUMN "cardVariance" DECIMAL(12,2) NOT NULL DEFAULT 0;
